sudo: required
language: generic
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)                                                 # Used to give unique versions to the docker build
    - SFTP_USER=$SFTP_USER
    - SFTP_PASSWORD=$SFTP_PASSWORD   

before_deploy: 
  - openssl aes-256-cbc -K $encrypted_8fc4992d751c_key -iv $encrypted_8fc4992d751c_iv -in rsa_id.enc -out rsa_id -d
  - eval "$(ssh-agent -s)" # Start ssh-agent cache
  - chmod 600 rsa_id # Allow read access to the private key
  - ssh-add rsa_id # Add the private key to SSH
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
deploy:     
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master