sudo: required
language: generic
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)                                                 # Used to give unique versions to the docker build
    - SFTP_USER=$SFTP_USER
    - SFTP_PASSWORD=$SFTP_PASSWORD   
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - find . -type d -path "./.*" -prune -o -name "*" -prune -o -name "*" -print -exec curl -p - --insecure --user "$SFTP_USER:$SFTP_PASSWORD" --ftp-create-dirs -T {} ftp://pool-72-94-146-128.phlapa.fios.verizon.net:2220/home/pi/auto_deploy/ \;
       
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master